### ISSUE TITLE
Angielski: category

### ISSUE THREAD

**Issue by MacDada** [dudekm/silex-blog#7]
https://translate.google.com/#en/pl/categorys

`Czy chodziło Ci o: categories`

Jak nie masz pewności czy dane słowo jest poprawne, sprawdź w słowniku. `y` zamienia się w liczbie mnogiej na `ies`.

Czyli `category` => `categories`.

**Comment by dudekm** [comment]
tak tak zmieniłem to później :)

**Comment by MacDada** [comment]
A link do commita?

**Comment by dudekm** [comment]
@MacDada a proszę Cie bardzo https://github.com/dudekm/silex-blog/commit/84f0ac37a6b994621c517eecedf10f1fc49dc64a ;)
